---
abstract: 'Multi-Thread URL Fetcher'
author:
  - 'satoshi azuma <ytnobody at gmail dot com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Kalas
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Coro: 0
  Coro::Semaphore: 0
  FurlX::Coro: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
